#!/data/data/com.termux/files/usr/bin/bash
#############################################
# DebDroid (Improved, debdroid-ng)
# All rights reserved (2020, 2021)
# 
# This script will launches Debian right from your Device
# For General system administering of commands and your debian system, see tldp.org and wiki.debian.org
#############################################
ROOTFS_DIR=placeholder

# Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

gen_proc_files(){
# /proc/stat
cat > "$ROOTFS_DIR/var/debdroid/binds/stat" <<- EOM
cpu  12713 0 4937 4003053 357 0 1023 0 0 0
intr 475303 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 1366979
btime 1612510849
processes 1459
procs_running 1
procs_blocked 0
softirq 656371 0 182183 2 125208 11139 0 18555 179609 417 139258
EOM
# /proc/version
cat > "$ROOTFS_DIR/var/debdroid/binds/version" <<- EOM
Linux version 5.1.0-debdroid (termux@android) (gcc version 8.2.4 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
EOM
# /proc/vmstat
cat > "$ROOTFS_DIR/var/debdroid/binds/vmstat" <<- EOM
nr_free_pages 685401
nr_zone_inactive_anon 2
nr_zone_active_anon 18085
nr_zone_inactive_file 24364
nr_zone_active_file 19257
nr_zone_unevictable 0
nr_zone_write_pending 0
nr_mlock 0
nr_page_table_pages 560
nr_kernel_stack 1728
nr_bounce 0
nr_free_cma 0
nr_inactive_anon 2
nr_active_anon 18085
nr_inactive_file 24364
nr_active_file 19257
nr_unevictable 0
nr_slab_reclaimable 4966
nr_slab_unreclaimable 2829
nr_isolated_anon 0
nr_isolated_file 0
workingset_refault 0
workingset_activate 0
workingset_nodereclaim 0
nr_anon_pages 18034
nr_mapped 8919
nr_file_pages 43632
nr_dirty 0
nr_writeback 0
nr_writeback_temp 0
nr_shmem 17
nr_shmem_hugepages 0
nr_shmem_pmdmapped 0
nr_anon_transparent_hugepages 7
nr_unstable 0
nr_vmscan_write 0
nr_vmscan_immediate_reclaim 0
nr_dirtied 52196
nr_written 44601
nr_dirty_threshold 141797
nr_dirty_background_threshold 70812
pgpgin 120682
pgpgout 4381340
pswpin 0
pswpout 0
pgalloc_dma 0
pgalloc_dma32 3418436
pgalloc_normal 0
pgalloc_movable 0
allocstall_dma 0
allocstall_dma32 0
allocstall_normal 0
allocstall_movable 0
pgskip_dma 0
pgskip_dma32 0
pgskip_normal 0
pgskip_movable 0
pgfree 4187429
pgactivate 31596
pgdeactivate 4
pglazyfree 55581
pgfault 1698575
pgmajfault 689
pglazyfreed 0
pgrefill 0
pgsteal_kswapd 0
pgsteal_direct 0
pgscan_kswapd 0
pgscan_direct 0
pgscan_direct_throttle 0
pginodesteal 0
slabs_scanned 0
kswapd_inodesteal 0
kswapd_low_wmark_hit_quickly 0
kswapd_high_wmark_hit_quickly 0
pageoutrun 0
pgrotated 4
drop_pagecache 0
drop_slab 0
oom_kill 0
pgmigrate_success 78914
pgmigrate_fail 7774
compact_migrate_scanned 2214562
compact_free_scanned 78434959
compact_isolated 170427
compact_stall 0
compact_fail 0
compact_success 0
compact_daemon_wake 0
compact_daemon_migrate_scanned 0
compact_daemon_free_scanned 0
htlb_buddy_alloc_success 0
htlb_buddy_alloc_fail 0
unevictable_pgs_culled 0
unevictable_pgs_scanned 0
unevictable_pgs_rescued 0
unevictable_pgs_mlocked 0
unevictable_pgs_munlocked 0
unevictable_pgs_cleared 0
unevictable_pgs_stranded 0
thp_fault_alloc 2149
thp_fault_fallback 0
thp_collapse_alloc 1332
thp_collapse_alloc_failed 0
thp_file_alloc 0
thp_file_mapped 0
thp_split_page 0
thp_split_page_failed 0
thp_deferred_split_page 2160
thp_split_pmd 11
thp_split_pud 0
thp_zero_page_alloc 0
thp_zero_page_alloc_failed 0
thp_swpout 0
thp_swpout_fallback 0
balloon_inflate 0
balloon_deflate 0
swap_ra 0
swap_ra_hit 0
EOM
# /proc/loadavg
cat > "$ROOTFS_DIR/var/debdroid/binds/loadavg" <<- EOM
0.00 0.00 0.00 1/105 1202
EOM
# /proc/uptime
cat > "$ROOTFS_DIR/var/debdroid/binds/uptime" <<- EOM
10.10 10.10
EOM
}

run_proot_cmd(){
gen_proc_files
prootcmd+="proot"
# Android 5/6 uses outdated proot, so we disable sysvipc
if [ ! "$(getprop ro.build.version.release)" == "5" ] && [ ! "$(getprop ro.build.version.release)" == "5.1" ] && [ ! "$(getprop ro.build.version.release)" == "5.1.1" ] && [ ! "$(getprop ro.build.version.release)" == "6" ] && [ ! "$(getprop ro.build.version.release)" == "6.0.1" ]; then
prootcmd+=" --sysvipc"
fi
prootcmd+=" -L -H -p"
prootcmd+=" --root-id --kernel-release=5.1.0-debdroid"
prootcmd+=" --rootfs=$ROOTFS_DIR"
prootcmd+=" --cwd=/root"
prootcmd+=" --bind=/dev"
prootcmd+=" --bind=/proc"
prootcmd+=" --bind=/sys"
prootcmd+=" --bind=$ROOTFS_DIR/run/shm:/dev/shm"
# The /var/debdroid/mounts.conf is a configuration file, source it if needed
source "$ROOTFS_DIR/var/debdroid/mounts.conf"
prootcmd+=" /usr/bin/env -i"
prootcmd+=" PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
prootcmd+=" HOME=/root"
prootcmd+=" TERM=$TERM"
prootcmd+=" LANG=C.UTF-8"
extcmd="${@}"
if [ ! -z "$extcmd" ]; then
    $prootcmd su -l `cat "$ROOTFS_DIR/etc/userinfo.db"` -c "$extcmd"
else
    $prootcmd su -l `cat "$ROOTFS_DIR/etc/userinfo.db"`
fi
}

run_proot_cmd_asroot(){
gen_proc_files
prootcmd+="proot"
# Android 5/6 uses outdated proot, so we disable sysvipc
if [ ! "$(getprop ro.build.version.release)" == "5" ] && [ ! "$(getprop ro.build.version.release)" == "5.1" ] && [ ! "$(getprop ro.build.version.release)" == "5.1.1" ] && [ ! "$(getprop ro.build.version.release)" == "6" ] && [ ! "$(getprop ro.build.version.release)" == "6.0.1" ]; then
prootcmd+=" --sysvipc"
fi
prootcmd+=" -L -H -p"
prootcmd+=" --root-id --kernel-release=5.1.0-debdroid"
prootcmd+=" --rootfs=$ROOTFS_DIR"
prootcmd+=" --cwd=/root"
prootcmd+=" --bind=/dev"
prootcmd+=" --bind=/proc"
prootcmd+=" --bind=/sys"
prootcmd+=" --bind=$ROOTFS_DIR/run/shm:/dev/shm"
# The /var/debdroid/mounts.conf is a configuration file, source it if needed
source "$ROOTFS_DIR/var/debdroid/mounts.conf"
prootcmd+=" /usr/bin/env -i"
prootcmd+=" PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
prootcmd+=" HOME=/root"
prootcmd+=" TERM=$TERM"
prootcmd+=" LANG=C.UTF-8"
extcmd="${@}"
if [ ! -z "$extcmd" ]; then
    $prootcmd su -l -c "$extcmd"
else
    $prootcmd su -l
fi
}

show_help(){
    echo "${GREEN}run-debian: enter Debian environment right from your Android Device"
    echo ""
    echo "Usage: run this command without arguments to login into your Debian Shell"
    echo " OPTIONS:"
    echo "${YELLOW} launch,run ${GREEN}- Run Debian as Regular User"
    echo "${YELLOW} launch-su,run-asroot,run-su,root ${GREEN}- Run Debian as Root User"
    echo ""
    echo "To Pass Command instead of bash shell, you can do"
    echo "${YELLOW}run-debian launch sudo apt update"
    echo "run-debian launch-su apt install hello${GREEN}"
    echo ""
    echo "To learn more the basics about debian, see: https://wiki.debian.org"
}

ARG="$1"
shift 1

case "$ARG" in
    login|launch|run)
        run_proot_cmd "$@"
        ;;
    login-su|login-asroot|root|launch-su|run|run-su|run-asroot)
        run_proot_cmd_asroot "$@"
        ;;
    help)
        show_help
        ;;
    *)
        run_proot_cmd "$@"
        ;;
esac

# End of Line EOL